{% set name = "hpv-kite" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hpdcj/HPV-KITE/archive/refs/tags/{{ version }}.tar.gz
  sha256: f4cae44c46114c2021506157722868688ca07518f2b88b185fadef00c72978b1

build:
  noarch: generic
  number: 0

requirements:
  build:
    - openjdk =21
    - sed
  run:
    - openjdk >=17

test:
  commands:
    - hpv-kite

about:
  home: https://github.com/hpdcj/HPV-KITE
  summary: "HPV-Kite: HPV K-mer Index Tversky Estimator application"
  description: |
    HPV-Kite is a Java application that detects HPV within samples.
    It can be used for DNA and/or RNA FASTQ files.
    KITE stands for K-mer Index Tversky Estimator, as the application leverages
    k-mer analysis combined with the Tversky index.
    HPV-Kite not only expedites viral detection but also maintains comparable
    sensitivity to existing approaches.
  license: BSD-3-Clause
  license_file: 
    - LICENSE
    - build/reports/dependency-license/ 


extra:
  recipe-maintainers:
    - faramir
